name: PC Application

on:
  push:
    branches:
      - qt
  pull_request:
    branches:
      - qt
        
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run linter
        uses: github/super-linter@v3
