name: Tests
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
    
jobs:
  hello_world:
    runs-on: epitechcontent/epitest-docker
    
    steps:
      - uses: actions/checkout@v2
        
      - shell: bash
        run: |
          make
          make tests_run
          make coverage
          
