name: Tests
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
    
jobs:
  hello_world:
    runs-on: ubuntu-20.04
    
    steps:
      - shell: bash
        run: echo Hello world
