name: Tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
    
jobs:
  hello_world:
    runs-on: ubuntu-20.04
    
    steps:
      - shell: bash
        run: echo Hello world!
    
  unit-tests:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    
    steps:
      - uses: actions/checkout@v2
      - run: |
          make tests_run >> result.txt
          make coverage >> result.txt
          
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage_outputs
          path: result.txt
      
  functional-tests:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    
    steps:
      - uses: actions/checkout@v2
      - run: |
          make
          chmod +x ./functional-test.sh
          ./functional-test.sh >> result.txt
          
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: function-tests_outputs
          path: result.txt
   
